version: "3.8"

services:
    react-app:
        build:
            context: react_app
            dockerfile: Dockerfile
        working_dir: /app
        environment:
            - NODE_ENV=production
        profiles: ["frontend"]
    api:
        build:
            context: api
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        working_dir: /app
        volumes:
            - ${STREAMS_FOLDER}:/streams/:ro 
        environment:
            - ROOT_DIR=/streams/
        profiles: ["backend"]
    nginx:
        image: nginx:1.20.2-alpine
        ports: 
            - ${PORT}:80
        volumes:
            - ${STREAMS_FOLDER}:/app/static/streams:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro 
        command: ["nginx", "-g", "daemon off;"]
        depends_on: 
            - api
            - react-app
        profiles: ["base"]

        